"""update portfolio model

Revision ID: 024a02c34196
Revises: c007e8f90964
Create Date: 2025-03-22 17:57:02.429165

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "024a02c34196"
down_revision: Union[str, None] = "c007e8f90964"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "columns",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("content", sa.String(length=10000), nullable=False),
        sa.Column("thumbnail_url", sa.String(length=255), nullable=True),
        sa.Column("author_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("view_count", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_columns_author_id"), "columns", ["author_id"], unique=False)
    op.create_table(
        "orders",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column(
            "package_type",
            sa.Enum("BASIC", "STANDARD", "PREMIUM", name="packagetype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PAID",
                "IN_PROGRESS",
                "COMPLETED",
                "CANCELLED",
                name="orderstatus",
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("requirements", sa.String(length=1000), nullable=True),
        sa.Column("logo_name", sa.String(length=100), nullable=False),
        sa.Column("logo_description", sa.String(length=500), nullable=True),
        sa.Column("design_data", sa.JSON(), nullable=False),
        sa.Column("image_url", sa.String(length=255), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_user_id"), "orders", ["user_id"], unique=False)
    op.create_table(
        "payments",
        sa.Column("order_id", sa.String(length=36), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "COMPLETED", "FAILED", "REFUNDED", name="paymentstatus"),
            nullable=False,
        ),
        sa.Column(
            "payment_method",
            sa.Enum("CARD", "BANK_TRANSFER", "VIRTUAL_ACCOUNT", name="paymentmethod"),
            nullable=False,
        ),
        sa.Column("payment_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("portone_payment_id", sa.String(length=100), nullable=True),
        sa.Column("portone_transaction_id", sa.String(length=100), nullable=True),
        sa.Column("refund_amount", sa.Integer(), nullable=True),
        sa.Column("refund_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_payments_order_id"), "payments", ["order_id"], unique=True)
    op.add_column("portfolios", sa.Column("display_order", sa.Integer(), nullable=False))
    op.add_column(
        "portfolios",
        sa.Column(
            "visibility",
            sa.Enum("PUBLIC", "PRIVATE", name="portfoliovisibility"),
            nullable=False,
        ),
    )
    op.alter_column(
        "portfolios",
        "category",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=50),
        type_=sa.Enum(
            "BRAND",
            "LOGO",
            "PACKAGING",
            "ILLUSTRATION",
            "OTHER",
            name="portfoliocategory",
        ),
        existing_nullable=False,
    )
    op.drop_index("ix_portfolios_category", table_name="portfolios")
    op.drop_column("portfolios", "is_visible")
    op.drop_column("portfolios", "order")
    op.drop_column("portfolios", "thumbnail_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "portfolios",
        sa.Column(
            "thumbnail_url",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=255),
            nullable=False,
        ),
    )
    op.add_column(
        "portfolios",
        sa.Column("order", mysql.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "portfolios",
        sa.Column(
            "is_visible",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_index("ix_portfolios_category", "portfolios", ["category"], unique=False)
    op.alter_column(
        "portfolios",
        "category",
        existing_type=sa.Enum(
            "BRAND",
            "LOGO",
            "PACKAGING",
            "ILLUSTRATION",
            "OTHER",
            name="portfoliocategory",
        ),
        type_=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=50),
        existing_nullable=False,
    )
    op.drop_column("portfolios", "visibility")
    op.drop_column("portfolios", "display_order")
    op.drop_index(op.f("ix_payments_order_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_orders_user_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_columns_author_id"), table_name="columns")
    op.drop_table("columns")
    # ### end Alembic commands ###
