"""add_category_to_column

Revision ID: 1bfe28a278bb
Revises: e99fcd513cef
Create Date: 2025-03-26 19:04:30.869341

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1bfe28a278bb"
down_revision: Union[str, None] = "e99fcd513cef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("columns", sa.Column("category", sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("columns", "category")
    # ### end Alembic commands ###
