"""add_thumbnail_url_to_column

Revision ID: aec3affc3fe8
Revises: 1bfe28a278bb
Create Date: 2025-03-26 19:05:10.073711

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aec3affc3fe8"
down_revision: Union[str, None] = "1bfe28a278bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("columns", sa.Column("thumbnail_url", sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("columns", "thumbnail_url")
    # ### end Alembic commands ###
