"""create_column_table

Revision ID: e99fcd513cef
Revises: 024a02c34196
Create Date: 2025-03-26 18:19:24.395471

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "e99fcd513cef"
down_revision: Union[str, None] = "024a02c34196"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Alter columns
    op.alter_column(
        "columns",
        "title",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=200),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "columns",
        "content",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=10000),
        type_=sa.Text(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "columns",
        "content",
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=10000),
        existing_nullable=False,
    )
    op.alter_column(
        "columns",
        "title",
        existing_type=sa.String(length=100),
        type_=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=200),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
